### PR TITLE
test(utils): add unit tests covering `formatReportScore`

### PR DESCRIPTION
**Pull request by LayZeeDK**
Part of #272.

## Test

- Add unit tests covering the internal function `formatReportScore` in `@code-pushup/utils`

### CODE REVIEW

**Review by BioPhoton — DISMISSED** [review]
Thx for the testing improvement

**Comment by BioPhoton** [comment]
Hi @LayZeeDK if you merge main the PR Labeler job should run now.

**Comment by LayZeeDK** [comment]
I don't think I have write access, @BioPhoton

**Review by BioPhoton — APPROVED** [review]
LGTM

**Pull request merged**
