### PR TITLE
ci: accept release publish

### PR DESCRIPTION
**Pull request by getlarge**
Solve publishing [issue](https://github.com/code-pushup/cli/pull/588#issuecomment-2022421081).

### CODE REVIEW

**Comment by getlarge** [comment]
@matejchalk First of all, I'm sorry for the 4 first dummy commits I pushed by mistake. Hopefully, merging this PR by squashing commits should hide them.

Second, I tried to generate the changelog and it seemed to work only after I cleaned up my mess with the git tags.
(I brutally removed all my local tags; you might want to try something more subtle...)

<details>

```sh

 >  NX   Running release version for project: plugin-js-packages

plugin-js-packages 🔍 Reading data for package "@code-pushup/js-packages-plugin" from packages/plugin-js-packages/package.json
plugin-js-packages 📄 Unable to resolve the current version from git tag using pattern "v{version}". Falling back to the version on disk of 0.29.0
plugin-js-packages 📄 Resolved the specifier as "minor" using git history and the conventional commits standard.
plugin-js-packages ✍️  New version 0.30.0 written to packages/plugin-js-packages/package.json

 >  NX   Running release version for project: plugin-coverage

plugin-coverage 🔍 Reading data for package "@code-pushup/coverage-plugin" from packages/plugin-coverage/package.json
plugin-coverage 📄 Using the current version 0.29.0 already resolved from disk fallback.
plugin-coverage ✍️  New version 0.30.0 written to packages/plugin-coverage/package.json

 >  NX   Running release version for project: plugin-eslint

plugin-eslint 🔍 Reading data for package "@code-pushup/eslint-plugin" from packages/plugin-eslint/package.json
plugin-eslint 📄 Using the current version 0.29.0 already resolved from disk fallback.
plugin-eslint ✍️  New version 0.30.0 written to packages/plugin-eslint/package.json

 >  NX   Running release version for project: models

models 🔍 Reading data for package "@code-pushup/models" from packages/models/package.json
models 📄 Using the current version 0.29.0 already resolved from disk fallback.
models ✍️  New version 0.30.0 written to packages/models/package.json
models ✍️  Applying new version 0.30.0 to 6 packages which depend on models

 >  NX   Running release version for project: utils

utils 🔍 Reading data for package "@code-pushup/utils" from packages/utils/package.json
utils 📄 Using the current version 0.29.0 already resolved from disk fallback.
utils ✍️  New version 0.30.0 written to packages/utils/package.json
utils ✍️  Applying new version 0.30.0 to 5 packages which depend on utils

 >  NX   Running release version for project: core

core 🔍 Reading data for package "@code-pushup/core" from packages/core/package.json
core 📄 Using the current version 0.29.0 already resolved from disk fallback.
core ✍️  New version 0.30.0 written to packages/core/package.json
core ✍️  Applying new version 0.30.0 to 1 package which depends on core

 >  NX   Running release version for project: cli

cli 🔍 Reading data for package "@code-pushup/cli" from packages/cli/package.json
cli 📄 Using the current version 0.29.0 already resolved from disk fallback.
cli ✍️  New version 0.30.0 written to packages/cli/package.json

UPDATE packages/plugin-js-packages/package.json [dry-run]

    "name": "@code-pushup/js-packages-plugin",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "dependencies": {
-     "@code-pushup/models": "*",
-     "@code-pushup/utils": "*",
+     "@code-pushup/models": "0.30.0",
+     "@code-pushup/utils": "0.30.0",
      "zod": "^3.22.4"

UPDATE packages/plugin-coverage/package.json [dry-run]

    "name": "@code-pushup/coverage-plugin",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "dependencies": {
-     "@code-pushup/models": "*",
-     "@code-pushup/utils": "*",
+     "@code-pushup/models": "0.30.0",
+     "@code-pushup/utils": "0.30.0",
      "parse-lcov": "^1.0.4",

UPDATE packages/plugin-eslint/package.json [dry-run]

    "name": "@code-pushup/eslint-plugin",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "license": "MIT",
    "dependencies": {
-     "@code-pushup/utils": "*",
-     "@code-pushup/models": "*",
+     "@code-pushup/utils": "0.30.0",
+     "@code-pushup/models": "0.30.0",
      "eslint": "^8.46.0",

UPDATE packages/models/package.json [dry-run]

    "name": "@code-pushup/models",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "license": "MIT",

UPDATE packages/utils/package.json [dry-run]

    "name": "@code-pushup/utils",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "dependencies": {
-     "@code-pushup/models": "*",
+     "@code-pushup/models": "0.30.0",
      "bundle-require": "^4.0.1",

UPDATE packages/core/package.json [dry-run]

    "name": "@code-pushup/core",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "license": "MIT",
    "dependencies": {
-     "@code-pushup/models": "*",
-     "@code-pushup/utils": "*",
+     "@code-pushup/models": "0.30.0",
+     "@code-pushup/utils": "0.30.0",
      "@code-pushup/portal-client": "^0.6.1",

UPDATE packages/cli/package.json [dry-run]

    "name": "@code-pushup/cli",
-   "version": "0.29.0",
+   "version": "0.30.0",
    "license": "MIT",

    "dependencies": {
-     "@code-pushup/models": "*",
-     "@code-pushup/core": "*",
+     "@code-pushup/models": "0.30.0",
+     "@code-pushup/core": "0.30.0",
      "yargs": "^17.7.2",
      "chalk": "^5.3.0",
-     "@code-pushup/utils": "*"
+     "@code-pushup/utils": "0.30.0"
    }


 >  NX   Staging changed files with git


NOTE: The "dryRun" flag means no changes were made.
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Previewing a GitHub release and an entry in CHANGELOG.md for v0.30.0

CREATE https://github.com/getlarge/cli/releases/tag/v0.30.0 [dry-run]

UPDATE CHANGELOG.md [dry-run]

+ ## 0.30.0 (2024-03-27)
+
+
+ ### 🚀 Features
+
+ - configure build and tests to handle ESM and CJS configs ([48cd967](https://github.com/getlarge/cli/commit/48cd967))
+ - support TS config files using Jiti + hackfix lighthouse import.meta usages ([3b7927d](https://github.com/getlarge/cli/commit/3b7927d))
+ - support top-level await in config files ([7712250](https://github.com/getlarge/cli/commit/7712250))
+ - add transform to persist config ([#229](https://github.com/getlarge/cli/pull/229))
+ - **cli:** use bundle-require instead of jiti (no hackfix, but also no CJS configs) ([028c592](https://github.com/getlarge/cli/commit/028c592))
+ - **cli:** setup yargs for cli ([#42](https://github.com/getlarge/cli/pull/42))
+ - **cli:** initial collect command ([#45](https://github.com/getlarge/cli/pull/45))
+ - **cli:** persist login and formatting options ([#47](https://github.com/getlarge/cli/pull/47))
+ - **cli:** disabled version option ([#162](https://github.com/getlarge/cli/pull/162))
+ - **cli:** add `--persist.filename` cli option ([#187](https://github.com/getlarge/cli/pull/187))
+ - **cli:** introduce the `onlyPlugins` option ([#246](https://github.com/getlarge/cli/pull/246))
+ - **cli:** add autoloading of the config file ([#361](https://github.com/getlarge/cli/pull/361))
+ - **cli:** add hints to commands ([#443](https://github.com/getlarge/cli/pull/443))
+ - **cli:** add logger ([#459](https://github.com/getlarge/cli/pull/459))
+ - **cli:** print full report url after upload ([0eb7771](https://github.com/getlarge/cli/commit/0eb7771))
+ - **cli:** add --tsconfig option ([67abfb7](https://github.com/getlarge/cli/commit/67abfb7))
+ - **cli:** include commit info in report.json ([5965900](https://github.com/getlarge/cli/commit/5965900))
+ - **cli:** implement compare command ([314e7ba](https://github.com/getlarge/cli/commit/314e7ba))
+ - **cli:** include md format by default ([65a08ea](https://github.com/getlarge/cli/commit/65a08ea))
+ - **core:** add core package ([dd8ddae](https://github.com/getlarge/cli/commit/dd8ddae))
+ - **core:** add esm plugin logic ([#248](https://github.com/getlarge/cli/pull/248))
+ - **core:** change to execute all plugins before throwing on failed ([#275](https://github.com/getlarge/cli/pull/275))
+ - **core:** improve upload error messages, extend icon set ([2251ebd](https://github.com/getlarge/cli/commit/2251ebd))
+ - **core:** add grouping of promise results by status ([5f50e8e](https://github.com/getlarge/cli/commit/5f50e8e))
+ - **core:** update portal-client to version with request timeouts ([173bd2f](https://github.com/getlarge/cli/commit/173bd2f))
+ - **core:** add optional upload.timeout to config ([fdc3f58](https://github.com/getlarge/cli/commit/fdc3f58))
+ - **core:** convert all issue file paths after executing plugin ([d82c68d](https://github.com/getlarge/cli/commit/d82c68d))
+ - **core:** implement categories, groups and audits comparisons ([72d6c14](https://github.com/getlarge/cli/commit/72d6c14))
+ - **core:** implement compare reports functions ([5493cc4](https://github.com/getlarge/cli/commit/5493cc4))
+ - **core:** add history logic ([#541](https://github.com/getlarge/cli/pull/541))
+ - **core:** create report-diff.md file if specified by persist.format ([8c4e1e4](https://github.com/getlarge/cli/commit/8c4e1e4))
+ - **examples-plugins:** add package-json plugin 📦 ([#354](https://github.com/getlarge/cli/pull/354))
+ - **examples-plugins:** add lighthouse to examples ([#417](https://github.com/getlarge/cli/pull/417))
+ - **models:** setup types and parser with zod ([7d5c99e](https://github.com/getlarge/cli/commit/7d5c99e))
+ - **models:** validate plugin icons using portal-client package ([f52cc75](https://github.com/getlarge/cli/commit/f52cc75))
+ - **models:** add isBinary field to category schema ([8b13039](https://github.com/getlarge/cli/commit/8b13039))
+ - **models:** add report filename option ([#174](https://github.com/getlarge/cli/pull/174))
+ - **models:** add missing schema exports ([36d3eea](https://github.com/getlarge/cli/commit/36d3eea))
+ - **models:** create reportsDiff schema ([75dc8aa](https://github.com/getlarge/cli/commit/75dc8aa))
+ - **nx-plugin:** initial setup and init command ([#51](https://github.com/getlarge/cli/pull/51))
+ - **nx-plugin:** add configuration generator ([#294](https://github.com/getlarge/cli/pull/294))
+ - **plugin-coverage:** set up plugin-coverage package ([8b18a0f](https://github.com/getlarge/cli/commit/8b18a0f))
+ - **plugin-coverage:** implement plugin configuration ([513c518](https://github.com/getlarge/cli/commit/513c518))
+ - **plugin-coverage:** implement lcov parsing ([800e2d0](https://github.com/getlarge/cli/commit/800e2d0))
+ - **plugin-coverage:** provide coverage group ([8cddfcd](https://github.com/getlarge/cli/commit/8cddfcd))
+ - **plugin-coverage:** add coverage tool run option, convert to runnerConfig ([d259c14](https://github.com/getlarge/cli/commit/d259c14))
+ - **plugin-coverage:** get coverage paths using nx ([cd499ea](https://github.com/getlarge/cli/commit/cd499ea))
+ - **plugin-coverage:** allow passing results as strings ([6813021](https://github.com/getlarge/cli/commit/6813021))
+ - **plugin-eslint:** register audit metadata based on eslintrc and file patterns ([3aac581](https://github.com/getlarge/cli/commit/3aac581))
+ - **plugin-eslint:** convert rule ids to slugs, add basic description to audits ([971c97a](https://github.com/getlarge/cli/commit/971c97a))
+ - **plugin-eslint:** rule options used to identify audit, options in slug (hash) and description ([b9f51c9](https://github.com/getlarge/cli/commit/b9f51c9))
+ - **plugin-eslint:** include NPM package name and version ([25bda11](https://github.com/getlarge/cli/commit/25bda11))
+ - **plugin-eslint:** validate initializer params with Zod ([56e1aee](https://github.com/getlarge/cli/commit/56e1aee))
+ - **plugin-eslint:** implement runner logic ([0ad5445](https://github.com/getlarge/cli/commit/0ad5445))
+ - **plugin-eslint:** configure bin entry point ([b34ecb2](https://github.com/getlarge/cli/commit/b34ecb2))
+ - **plugin-eslint:** create groups from rules' meta.type (problem/suggestion/layout) ([0350e49](https://github.com/getlarge/cli/commit/0350e49))
+ - **plugin-eslint:** create groups from rules' meta.docs.category (per plugin) ([56e129c](https://github.com/getlarge/cli/commit/56e129c))
+ - **plugin-eslint:** add support for inline eslint config ([67571eb](https://github.com/getlarge/cli/commit/67571eb))
+ - **plugin-eslint:** provide Nx helper to combine eslint config from all projects ([82fa3e1](https://github.com/getlarge/cli/commit/82fa3e1))
+ - **plugin-eslint:** provide Nx helper to combine eslint configs from project with deps ([29cd887](https://github.com/getlarge/cli/commit/29cd887))
+ - **plugin-eslint:** add docs url ([d6a6b2a](https://github.com/getlarge/cli/commit/d6a6b2a))
+ - **plugin-eslint:** set "passed" displayValue for ESLint audits ([40f61a4](https://github.com/getlarge/cli/commit/40f61a4))
+ - **plugin-js-packages:** implement plugin schema and configuration flow ([e2ce3f6](https://github.com/getlarge/cli/commit/e2ce3f6))
+ - **plugin-js-packages:** use group per check, audit per dependency group ([1405e7d](https://github.com/getlarge/cli/commit/1405e7d))
+ - **plugin-js-packages:** implement runner for npm audit ([6aa55a2](https://github.com/getlarge/cli/commit/6aa55a2))
+ - **plugin-js-packages:** implement runner for npm outdated ([7cb623b](https://github.com/getlarge/cli/commit/7cb623b))
+ - **plugin-js-packages:** add runner config integration test, restructure runner ([cae4ca8](https://github.com/getlarge/cli/commit/cae4ca8))
+ - **plugin-js-packages:** improve output, scoring, error handling ([b9f1432](https://github.com/getlarge/cli/commit/b9f1432))
+ - **plugin-js-packages:** introduce yarn v1 outdated, unify type ([ca7905a](https://github.com/getlarge/cli/commit/ca7905a))
+ - **plugin-js-packages:** introduce yarn v1 audit, unify type ([ee3209d](https://github.com/getlarge/cli/commit/ee3209d))
+ - **plugin-js-packages:** process audit and outdated for different package managers ([3218162](https://github.com/getlarge/cli/commit/3218162))
+ - **plugin-js-packages:** fix npm v10 behaviour, parse json-lines ([daa5c5d](https://github.com/getlarge/cli/commit/daa5c5d))
+ - **plugin-lighthouse:** add onlyAudits logic ([#472](https://github.com/getlarge/cli/pull/472))
+ - **plugin-lighthouse:** add only filters logic for categories ([#515](https://github.com/getlarge/cli/pull/515))
+ - **plugin-lighthouse:** implement basic audit parsing ([#523](https://github.com/getlarge/cli/pull/523))
+ - **utils:** add package `utils` for cli independent logic ([#39](https://github.com/getlarge/cli/pull/39))
+ - **utils:** add command line args helper ([#52](https://github.com/getlarge/cli/pull/52))
+ - **utils:** add file size logging ([#65](https://github.com/getlarge/cli/pull/65))
+ - **utils:** move parts from utils into core ([#81](https://github.com/getlarge/cli/pull/81))
+ - **utils:** add upload logic ([#66](https://github.com/getlarge/cli/pull/66))
+ - **utils:** implement verbose helper logic ([#121](https://github.com/getlarge/cli/pull/121))
+ - **utils:** add scoring logic ([#133](https://github.com/getlarge/cli/pull/133))
+ - **utils:** implement report.md formatting ([#196](https://github.com/getlarge/cli/pull/196))
+ - **utils:** update git latest commit functionality ([#205](https://github.com/getlarge/cli/pull/205))
+ - **utils:** implement a new design for stdout ([#206](https://github.com/getlarge/cli/pull/206))
+ - **utils:** add audits sorting for reports ([#302](https://github.com/getlarge/cli/pull/302))
+ - **utils:** add file-system helper ([#336](https://github.com/getlarge/cli/pull/336))
+ - **utils:** add utility function for truncating texts ([bdce572](https://github.com/getlarge/cli/commit/bdce572))
+ - **utils:** add sorting of audit issues for report md ([b1c5dd7](https://github.com/getlarge/cli/commit/b1c5dd7))
+ - **utils:** include timezone in report.md ([27d267a](https://github.com/getlarge/cli/commit/27d267a))
+ - **utils:** implement helpers for making paths relative to git root ([b12df6d](https://github.com/getlarge/cli/commit/b12df6d))
+ - **utils:** add git helper ([#469](https://github.com/getlarge/cli/pull/469))
+ - **utils:** add helper functions for diffing ([4e87cd5](https://github.com/getlarge/cli/commit/4e87cd5))
+ - **utils:** implement markdown diff formatting ([5f453ef](https://github.com/getlarge/cli/commit/5f453ef))
+ - **utils:** improve reports diff formatting ([2bee85e](https://github.com/getlarge/cli/commit/2bee85e))
+ - **utils:** handle unchanged reports diff ([0cdcb9e](https://github.com/getlarge/cli/commit/0cdcb9e))
+ - **utils:** sort changed categories/groups/audits by most affected ([74cb57e](https://github.com/getlarge/cli/commit/74cb57e))
+ - **utils:** include unchanged and added categories in markdown table ([4e53077](https://github.com/getlarge/cli/commit/4e53077))
+ - **utils:** improve diff md formatting - change icon, n/a cells, percentage space ([27290f2](https://github.com/getlarge/cli/commit/27290f2))
+ - **utils:** use auto-link commit format (GitHub/GitLab) in markdown ([2f26c6c](https://github.com/getlarge/cli/commit/2f26c6c))
+
+ ### 🔥 Performance
+
+ - **utils:** add benchmark logic and example ([#137](https://github.com/getlarge/cli/pull/137))
+ - **utils:** improve the performance of scoring and reporting ([#212](https://github.com/getlarge/cli/pull/212))
+ - **utils:** setup microbenchmark for crawlFileSystem ([#355](https://github.com/getlarge/cli/pull/355))
+ - **utils:** add benchmarks for file system walk and glob libs ([#514](https://github.com/getlarge/cli/pull/514))
+
+ ### 🩹 Fixes
+
+ - sync package-lock.json with `npm install` ([0fde5f3](https://github.com/getlarge/cli/commit/0fde5f3))
+ - formatting ([7e5e743](https://github.com/getlarge/cli/commit/7e5e743))
+ - lint config and errors ([6f5f677](https://github.com/getlarge/cli/commit/6f5f677))
+ - refactor after core package intro ([#83](https://github.com/getlarge/cli/pull/83))
+ - stop CLI when a plugin fails ([263537c](https://github.com/getlarge/cli/commit/263537c))
+ - package json lock ([#562](https://github.com/getlarge/cli/pull/562))
+ - **cli:** run `npm install` before tests ([6507c2e](https://github.com/getlarge/cli/commit/6507c2e))
+ - **cli:** changed persist format options to array ([#153](https://github.com/getlarge/cli/pull/153))
+ - **cli:** parse multiple config args to last item of array ([#164](https://github.com/getlarge/cli/pull/164))
+ - **cli:** replace clui on @isaacs/cliui ([#282](https://github.com/getlarge/cli/pull/282))
+ - **cli:** exclude nested kebab-case keys, update tests ([741d5a5](https://github.com/getlarge/cli/commit/741d5a5))
+ - **cli:** fix json format handling ([#360](https://github.com/getlarge/cli/pull/360))
+ - **cli:** adjust persist.format options ([#363](https://github.com/getlarge/cli/pull/363))
+ - **cli:** set terminal output to full width ([#362](https://github.com/getlarge/cli/pull/362))
+ - **cli:** make onlyPlugins filter based on plugin not audit/group slug ([e963c36](https://github.com/getlarge/cli/commit/e963c36))
+ - **cli:** fix missing executable permissions for index.js ([0fd2eb4](https://github.com/getlarge/cli/commit/0fd2eb4))
+ - **cli-e2e:** re-create package-lock.json ([8a99ec0](https://github.com/getlarge/cli/commit/8a99ec0))
+ - **core:** audit metadata looked up in plugin config, not expected in output ([31ffd5e](https://github.com/getlarge/cli/commit/31ffd5e))
+ - **core:** include package.json data ([0fef0c3](https://github.com/getlarge/cli/commit/0fef0c3))
+ - **core:** update portal-client, fixed missing graphql dependency ([c16c0c8](https://github.com/getlarge/cli/commit/c16c0c8))
+ - **core:** upload issue without source if file not linked ([2923dbd](https://github.com/getlarge/cli/commit/2923dbd))
+ - **core:** ensure output directory exists in compareReportFiles ([cf309bc](https://github.com/getlarge/cli/commit/cf309bc))
+ - **models:** add package.lock ([8075613](https://github.com/getlarge/cli/commit/8075613))
+ - **models:** allow empty string as docsUrl ([1c34d92](https://github.com/getlarge/cli/commit/1c34d92))
+ - **models:** increase character limit for issue message ([e6f6fc8](https://github.com/getlarge/cli/commit/e6f6fc8))
+ - **models:** fix use case for a group reference but empty audits, clean up tests ([d311b95](https://github.com/getlarge/cli/commit/d311b95))
+ - **models:** issue file positions must be positive integers ([727926e](https://github.com/getlarge/cli/commit/727926e))
+ - **plugin-coverage:** calculate coverage for no found entities as full coverage ([349c772](https://github.com/getlarge/cli/commit/349c772))
+ - **plugin-coverage:** convert new lines on Windows for parse-lcov, update docs ([3195da2](https://github.com/getlarge/cli/commit/3195da2))
+ - **plugin-eslint:** exclude rules which are turned off ([f2cc454](https://github.com/getlarge/cli/commit/f2cc454))
+ - **plugin-eslint:** ensure runner output directory exists ([fca87f5](https://github.com/getlarge/cli/commit/fca87f5))
+ - **plugin-eslint:** pluralize audit display value based on count ([aa35d0c](https://github.com/getlarge/cli/commit/aa35d0c))
+ - **plugin-eslint:** handle implicitly relative config paths ([39a7d43](https://github.com/getlarge/cli/commit/39a7d43))
+ - **plugin-eslint:** omit empty docsUrl in audit metadata ([3127683](https://github.com/getlarge/cli/commit/3127683))
+ - **plugin-eslint:** allow unmatched patterns ([d350187](https://github.com/getlarge/cli/commit/d350187))
+ - **plugin-eslint:** ensure working directory exists before writing .eslintrc.json ([3f19d6f](https://github.com/getlarge/cli/commit/3f19d6f))
+ - **plugin-eslint:** dynamic import for optional peer dep @nx/devkit ([ab62f2f](https://github.com/getlarge/cli/commit/ab62f2f))
+ - **plugin-eslint:** truncate rule texts to pass models validations ([a6aac56](https://github.com/getlarge/cli/commit/a6aac56))
+ - **plugin-eslint:** set default lint file patterns for Nx projects ([9db19d0](https://github.com/getlarge/cli/commit/9db19d0))
+ - **plugin-eslint:** fix default Nx lint patterns - directory not valid for "files" in eslintrc ([6865800](https://github.com/getlarge/cli/commit/6865800))
+ - **plugin-eslint:** truncate long issue messages ([c39d0cc](https://github.com/getlarge/cli/commit/c39d0cc))
+ - **plugin-eslint:** handle rules which emit column 0 ([de791e1](https://github.com/getlarge/cli/commit/de791e1))
+ - **plugin-eslint:** pass arguments via config file instead of argv ([dca0266](https://github.com/getlarge/cli/commit/dca0266))
+ - **plugin-eslint:** eslint startline can be zero ([#563](https://github.com/getlarge/cli/pull/563))
+ - **plugin-eslint:** allow minor updates to eslint dependency ([efbe028](https://github.com/getlarge/cli/commit/efbe028))
+ - **testing:** fix tests for Windows ([#165](https://github.com/getlarge/cli/pull/165))
+ - **utils:** handle descriptions ending in code block in report.md ([a9a05ad](https://github.com/getlarge/cli/commit/a9a05ad))
+ - **utils:** set fixed locale for date in report.md ([aa4694b](https://github.com/getlarge/cli/commit/aa4694b))
+ - **utils:** sort groups and category refs correctly in report ([76a7636](https://github.com/getlarge/cli/commit/76a7636))
+ - **utils:** use shields.io for colorizing changed values ([d0eb475](https://github.com/getlarge/cli/commit/d0eb475))
+ - **utils:** literal asterisk in Markdown doc should be escaped ([6348ba3](https://github.com/getlarge/cli/commit/6348ba3))
+ - **utils:** prevent mixed summary when some audit changed only value ([20673fd](https://github.com/getlarge/cli/commit/20673fd))
+ - **utils:** use unicode arrows with wider OS support ([271155e](https://github.com/getlarge/cli/commit/271155e))
+ - **utils,cli:** remove all mentions of the `interactive` option ([#245](https://github.com/getlarge/cli/pull/245))
+ - **workflows:** update and improve labeler options ([146434a](https://github.com/getlarge/cli/commit/146434a))
+
+ ### ❤️  Thank You
+
+ - Igor Katsuba @IKatsuba
+ - Katerina Pilatova
+ - Kateřina Pilátová
+ - Markus Nissl
+ - Matěj Chalk @matejchalk
+ - Michael @rx-angular
+ - Michael Hladky @BioPhoton
+ - Michael Seredenko @MishaSeredenkoPushBased
+
  # Changelog

  This file was generated using [@jscutlery/semver](https://github.com/jscutlery/semver).


 >  NX   Staging changed files with git


NOTE: The "dryRun" flag means no changelogs were actually created.

 >  NX   Committing changes with git


 >  NX   Tagging commit with git

Skipped publishing packages.
```

</details>

This time, it generates a new changelog with all the past commits caught by the default conventional commit rules.

**Comment by getlarge** [comment]
You can see what the release would look like [here](https://github.com/getlarge/cli/releases/tag/v0.30.0)

**Review by matejchalk — APPROVED** [review]
Thanks, will give it a try :crossed_fingers:

**Comment by matejchalk** [comment]
So, it does create the GitHub release and tags the commit. But for some reason it skips publishing to NPM. There's a bunch of [`Skipped package ... because <older-version> already exists ...` logs](https://github.com/code-pushup/cli/actions/runs/8467225710/job/23197661488#step:7:242), which I don't understand because they reference a different version (`0.29.0`) than what's being correctly calculated (`0.31.0`) in the logs above :confused: 

Also, it seems to commit something and not push it (there's no `release: ...` commit), which causes the subsequent [Code PushUp step to error](https://github.com/code-pushup/cli/actions/runs/8467225710/job/23197661488#step:8:566) (it looks up the current commit with `git log -1`). No clue what's happening there.

**Comment by getlarge** [comment]
> So, it does create the GitHub release and tags the commit. But for some reason it skips publishing to NPM. There's a bunch of [`Skipped package ... because <older-version> already exists ...` logs](https://github.com/code-pushup/cli/actions/runs/8467225710/job/23197661488#step:7:242), which I don't understand because they reference a different version (`0.29.0`) than what's being correctly calculated (`0.31.0`) in the logs above 😕
> 
> Also, it seems to commit something and not push it (there's no `release: ...` commit), which causes the subsequent [Code PushUp step to error](https://github.com/code-pushup/cli/actions/runs/8467225710/job/23197661488#step:8:566) (it looks up the current commit with `git log -1`). No clue what's happening there.

At first sight, i don't know the reasons for this behaviour, i'll have a look.
In the meantime, you could try to publish manually with `nx release publish` and tell me the output.

**Comment by matejchalk** [comment]
> If the package.json files located under the packages have the correct version (>0.29), could you try to run the build (skipping the cache) separately and then release publish?

Ok, that worked. I actually forgot about `--skipNxCache`, but it didn't seem to matter. 

What I did:
1. moved `git` property to sub-commands
    ```patch
   diff --git a/nx.json b/nx.json
   index 1534aeddd..5362bc27b 100644
   --- a/nx.json
   +++ b/nx.json
   @@ -99,19 +99,22 @@
          "projectChangelogs": false,
          "workspaceChangelog": {
            "createRelease": "github"
   +      },
   +      "git": {
   +        "commit": true,
   +        "tag": true,
   +        "commitMessage": "release: {version} [skip ci]"
          }
        },
   -    "git": {
   -      "commit": true,
   -      "push": true,
   -      "pushRemote": "origin",
   -      "tag": true,
   -      "commitMessage": "release: {version} [skip ci]"
   -    },
        "version": {
          "conventionalCommits": true,
          "generatorOptions": {
            "skipLockFileUpdate": true
   +      },
   +      "git": {
   +        "commit": true,
   +        "tag": true,
   +        "commitMessage": "release: {version} [skip ci]"
          }
        },
        "releaseTagPattern": "v{version}"
   
    ```
2. ran `npx nx release version 0.34.0`
    - without specifying version it didn't want to update from `0.33.0`, even when I added a new `fix: ...` commit :confused: 
3. ran `npx nx release changelog 0.34.0`
    - this actually created another `release: 0.34.0 [skip ci]` commit and then failed because of duplicate `v0.34.0` tag, but it did updated the `CHANGELOG.md` correctly
    - also it logged a succesful `CREATE https://github.com/code-pushup/cli/releases/tag/v0.34.0` message, but the GitHub release doesn't exist
4. ran `npx nx release publish`
    - succesfully published all the packages to NPM
    - forgot about skipping cache, but the builds were actually run anyway

So, not quite there yet with the automation, but at least I now have to some workaround to publish all packages manually :sweat_smile:

**Comment by getlarge** [comment]
in fact something that could make it easier until having a stable flow:
1. `npx nx release --skip-publish` (would trigger both `version` and `changelog` commands
2. `git push --follow-tags`
3. `npx nx release publish`

**Pull request merged**
